env: 
  name: app workflow

on:
  push:
    branches: 
     - main

jobs:
  test:
     runs-on: ubuntu-latest
     steps:
        - name: get code
          uses: actions/checkout@v4

        - name: say hello
          run: echo $name

        - name: list files
          run: ls

  build: 
     needs: test
     runs-on: ubuntu-latest
     steps: 
        - name: running dependencies
          run: echo "hello this is another job"

